ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_username_key";

ALTER TABLE "User" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Attendance" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Product" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Batch" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Customer" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Sale" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "DeliveryProof" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Purchase" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PurchaseItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SaleReturn" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "SaleReturnItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PurchaseReturn" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PurchaseReturnItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Notification" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "BusinessProfile" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Visit" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Order" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Route" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "RouteStop" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "LocationLog" ADD COLUMN "tenantId" TEXT;

CREATE UNIQUE INDEX "User_tenantId_username_key" ON "User"("tenantId", "username");

CREATE INDEX "User_tenantId_idx" ON "User"("tenantId");
CREATE INDEX "Attendance_tenantId_idx" ON "Attendance"("tenantId");
CREATE INDEX "Product_tenantId_idx" ON "Product"("tenantId");
CREATE INDEX "Batch_tenantId_idx" ON "Batch"("tenantId");
CREATE INDEX "Customer_tenantId_idx" ON "Customer"("tenantId");
CREATE INDEX "Supplier_tenantId_idx" ON "Supplier"("tenantId");
CREATE INDEX "Sale_tenantId_idx" ON "Sale"("tenantId");
CREATE INDEX "DeliveryProof_tenantId_idx" ON "DeliveryProof"("tenantId");
CREATE INDEX "SaleItem_tenantId_idx" ON "SaleItem"("tenantId");
CREATE INDEX "Purchase_tenantId_idx" ON "Purchase"("tenantId");
CREATE INDEX "PurchaseItem_tenantId_idx" ON "PurchaseItem"("tenantId");
CREATE INDEX "SaleReturn_tenantId_idx" ON "SaleReturn"("tenantId");
CREATE INDEX "SaleReturnItem_tenantId_idx" ON "SaleReturnItem"("tenantId");
CREATE INDEX "PurchaseReturn_tenantId_idx" ON "PurchaseReturn"("tenantId");
CREATE INDEX "PurchaseReturnItem_tenantId_idx" ON "PurchaseReturnItem"("tenantId");
CREATE INDEX "Notification_tenantId_idx" ON "Notification"("tenantId");
CREATE INDEX "BusinessProfile_tenantId_idx" ON "BusinessProfile"("tenantId");
CREATE INDEX "audit_logs_tenantId_idx" ON "audit_logs"("tenantId");
CREATE INDEX "Visit_tenantId_idx" ON "Visit"("tenantId");
CREATE INDEX "Order_tenantId_idx" ON "Order"("tenantId");
CREATE INDEX "OrderItem_tenantId_idx" ON "OrderItem"("tenantId");
CREATE INDEX "Route_tenantId_idx" ON "Route"("tenantId");
CREATE INDEX "RouteStop_tenantId_idx" ON "RouteStop"("tenantId");
CREATE INDEX "LocationLog_tenantId_idx" ON "LocationLog"("tenantId");

ALTER TABLE "User" ADD CONSTRAINT "User_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Batch" ADD CONSTRAINT "Batch_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DeliveryProof" ADD CONSTRAINT "DeliveryProof_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SaleItem" ADD CONSTRAINT "SaleItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PurchaseItem" ADD CONSTRAINT "PurchaseItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SaleReturn" ADD CONSTRAINT "SaleReturn_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SaleReturnItem" ADD CONSTRAINT "SaleReturnItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PurchaseReturn" ADD CONSTRAINT "PurchaseReturn_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PurchaseReturnItem" ADD CONSTRAINT "PurchaseReturnItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BusinessProfile" ADD CONSTRAINT "BusinessProfile_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Visit" ADD CONSTRAINT "Visit_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Route" ADD CONSTRAINT "Route_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RouteStop" ADD CONSTRAINT "RouteStop_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LocationLog" ADD CONSTRAINT "LocationLog_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TenantBranding"("id") ON DELETE SET NULL ON UPDATE CASCADE;
